import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RoboRetiever",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main>
        {children}
        </main>
      
      </body>
    </html>
  );
}
